name: '🚀 Feature request'
description: Suggest a feature that will improve LC-Library
labels: ['💡pending triage']
body:
  - type: checkboxes
    id: lib
    attributes:
      label: Select the package
      description: 选择对应的库
      options:
        - label: '@noahyu/lc-ui'
        - label: '@noahyu/lc-helpers'
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: 请描述您希望具备的功能
    validations:
      required: true
  - type: checkboxes
    id: PR
    attributes:
      label: Additional information
      description: 我们还想了解更多的信息.
      options:
        - label: 您是否有提交 PR 的计划?
        - label: 您是否急需使用此功能?
